// VS Code language ID → Prism.js language alias
export const LANG_MAP: Record<string, string> = {
  typescript: 'typescript',
  typescriptreact: 'tsx',
  javascript: 'javascript',
  javascriptreact: 'jsx',
  python: 'python',
  java: 'java',
  c: 'c',
  cpp: 'cpp',
  csharp: 'csharp',
  go: 'go',
  rust: 'rust',
  ruby: 'ruby',
  php: 'php',
  swift: 'swift',
  kotlin: 'kotlin',
  html: 'markup',
  xml: 'markup',
  css: 'css',
  scss: 'scss',
  less: 'less',
  json: 'json',
  yaml: 'yaml',
  markdown: 'markdown',
  shell: 'bash',
  shellscript: 'bash',
  powershell: 'powershell',
  lua: 'lua',
  r: 'r',
  dart: 'dart',
  scala: 'scala',
  groovy: 'groovy',
  perl: 'perl',
};

/** Prism token class → candidate TextMate scope(s), most-specific first. */
export const PRISM_TO_TEXTMATE: Record<string, string[]> = {
  'comment':     ['comment'],
  'prolog':      ['comment'],
  'doctype':     ['comment'],
  'cdata':       ['comment'],
  'punctuation': ['punctuation'],
  'property':    ['variable.other.property', 'support.type.property-name', 'entity.name.tag'],
  'tag':         ['entity.name.tag'],
  'constant':    ['constant'],
  'symbol':      ['constant.other.symbol', 'constant'],
  'deleted':     ['markup.deleted'],
  'boolean':     ['constant.language'],
  'number':      ['constant.numeric'],
  'selector':    ['entity.other.attribute-name.class'],
  'attr-name':   ['entity.other.attribute-name'],
  'string':      ['string'],
  'char':        ['string', 'constant.character'],
  'builtin':     ['support.class', 'support.type'],
  'inserted':    ['markup.inserted'],
  'operator':    ['keyword.operator'],
  'entity':      ['constant.character.entity'],
  'url':         ['markup.underline.link', 'string'],
  'atrule':      ['keyword.control.at-rule', 'keyword'],
  'attr-value':  ['string'],
  'keyword':     ['keyword', 'keyword.control', 'storage.type', 'storage.modifier'],
  'function':    ['entity.name.function', 'support.function'],
  'class-name':  ['entity.name.type', 'support.type', 'support.class'],
  'regex':       ['string.regexp'],
  'important':   ['keyword.other.important', 'keyword'],
  'variable':    ['variable', 'variable.other'],
};
